[package]
name = "rsh"
version = "0.1.0"
edition = "2018"

[profile.release]
opt-level = 'z'
strip = true
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
libc = "0.2"
ctrlc = "3.2.1"
lazy_static = "1.4.0"